# Generated by Django 3.0.6 on 2020-11-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('paytime', models.DateTimeField()),
                ('payment', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='book_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('breakfast', models.IntegerField()),
                ('adult_num', models.IntegerField()),
                ('child_num', models.IntegerField()),
                ('baby_num', models.IntegerField()),
                ('extra_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_check_in', models.BooleanField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='booking_parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('booking_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='card_info',
            fields=[
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=30)),
                ('cvc', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('card_number1', models.BooleanField()),
                ('card_number2', models.BooleanField()),
                ('card_number3', models.BooleanField()),
                ('card_number4', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='card_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coupon_list',
            fields=[
                ('coupon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('member_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customer_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='depart',
            fields=[
                ('depart_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='engineering',
            fields=[
                ('facility_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='engineering_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=100)),
                ('check_date', models.DateTimeField()),
                ('check_limit', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='engineering_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('facility_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='event_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contents', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='event_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='in_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('order_time', models.DateTimeField()),
                ('offer_time', models.DateTimeField()),
                ('is_payment', models.BooleanField()),
                ('count', models.IntegerField()),
                ('booking_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member_info',
            fields=[
                ('member_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('membership', models.CharField(max_length=30)),
                ('birth', models.DateTimeField()),
                ('is_sms', models.BooleanField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('car_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('spot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('purchase_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_slip',
            fields=[
                ('purchase_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('is_purchase', models.BooleanField()),
                ('staff_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('room_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room_type_bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(max_length=30)),
                ('bed_num', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_num', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('depart_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=30)),
                ('detail_address', models.CharField(max_length=100)),
                ('wide_area_unit', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='staff_day_off_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('off_start', models.DateTimeField()),
                ('off_end', models.DateTimeField()),
                ('day_off_type', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='staff_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_working_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('x_day', models.CharField(max_length=30)),
                ('work_time_start', models.DateTimeField()),
                ('work_time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='team_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='widearea_street',
            fields=[
                ('wide_area_unit', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=30)),
                ('basic_unit', models.CharField(max_length=30)),
                ('si_gu', models.CharField(max_length=30)),
                ('eub_myeon', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
