# Generated by Django 3.0.6 on 2020-11-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20201115_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_content',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event'),
        ),
    ]
