# Generated by Django 3.0.6 on 2020-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20201115_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='card_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_request',
            name='extra_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='offer_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff_address',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='widearea_street',
            name='basic_unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='widearea_street',
            name='eub_myeon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='widearea_street',
            name='si_gu',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
