# Generated by Django 3.0.6 on 2020-11-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_tmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tmp',
        ),
    ]
