# Generated by Django 3.0.6 on 2020-11-16 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_delete_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineering_content',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='event_content',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='member_email',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='member_phone',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='widearea_street',
        ),
        migrations.AddField(
            model_name='engineering',
            name='check_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineering',
            name='check_limit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineering',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contents',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_info',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_info',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_info',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_info',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_address',
            name='basic_unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff_address',
            name='eub_myeon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff_address',
            name='si_gu',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='engineering_content',
        ),
        migrations.DeleteModel(
            name='event_content',
        ),
        migrations.DeleteModel(
            name='member_email',
        ),
        migrations.DeleteModel(
            name='member_phone',
        ),
    ]
