# Generated by Django 3.0.6 on 2020-11-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20201116_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_phone',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff_info',
            name='account',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_info',
            name='bank',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_info',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book_request',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_phone',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='in_storage',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member_customer',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_address',
            name='staff_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_info',
            name='staff_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='staff_account',
        ),
        migrations.DeleteModel(
            name='staff_phone',
        ),
    ]
