# Generated by Django 3.0.6 on 2020-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20201116_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depart',
            name='depart_id',
            field=models.CharField(max_length=100),
        ),
    ]
