# Generated by Django 3.0.6 on 2020-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20201116_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff_info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team_staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff_address',
            name='staff_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff_info',
            name='staff_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team_staff',
            name='staff_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
