# Generated by Django 3.0.6 on 2020-11-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20201116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paytime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card_info',
            name='expiration_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='check_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='check_limit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='offer_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member_info',
            name='birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase_slip',
            name='delivery_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase_slip',
            name='order_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_day_off_info',
            name='off_end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_day_off_info',
            name='off_start',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_working_info',
            name='work_time_end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_working_info',
            name='work_time_start',
            field=models.CharField(max_length=20),
        ),
    ]
