# Generated by Django 3.0.6 on 2020-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20201117_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='mem_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
