# Generated by Django 3.0.6 on 2020-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20201120_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_list',
            fields=[
                ('coupon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coupon_type', models.CharField(max_length=100)),
                ('coupon_name', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('member_id', models.CharField(max_length=100)),
            ],
        ),
    ]
