# Generated by Django 3.0.6 on 2020-11-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_coupon_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_info',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
