# Generated by Django 3.0.6 on 2020-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_member_info_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='photo_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
